# Generated by Django 6.1 on 2026-08-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="candidate",
            name="candidates__skills_8595db_gin",
        ),
    ]
