# Generated by Django 6.1 on 2026-08-26 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0002_remove_candidate_candidates__skills_8595db_gin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="user",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
