# Generated by Django 6.1 on 2026-08-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0003_candidate_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="experience_years",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="resume_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="skills",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
