# Generated by Django 6.1 on 2026-09-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0005_outboxevent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outboxevent",
            name="event_type",
        ),
    ]
