# Generated by Django 6.1 on 2026-09-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0006_remove_outboxevent_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="resume_object_key",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
