# Generated by Django 6.1 on 2026-08-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="candidate_email",
        ),
        migrations.RemoveField(
            model_name="application",
            name="candidate_location",
        ),
        migrations.RemoveField(
            model_name="application",
            name="candidate_name",
        ),
        migrations.RemoveField(
            model_name="application",
            name="candidate_skills",
        ),
        migrations.RemoveField(
            model_name="application",
            name="experience_years",
        ),
        migrations.AddField(
            model_name="application",
            name="candidate_data",
            field=models.JSONField(default=dict),
        ),
    ]
