# Generated by Django 6.1 on 2026-09-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_outboxevent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outboxevent",
            name="event_type",
        ),
    ]
