# Generated by Django 6.1 on 2026-09-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_remove_outboxevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outboxevent",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("PUBLISHED", "Published")],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
